### PR TITLE
Update NativeMailerHandler.php

### PR DESCRIPTION
**Pull request by glensc**
don't calculate parameters in a loop

### CODE REVIEW

**Comment by glensc** [comment]
note, i initially committed with a typo (64fc8534849ab728b6d16960d03a3cfa20928527), seems testcase did not catch this!

```
All checks have passed
1 successful check
```

**Comment by Seldaek** [comment]
Thanks, it's a minor improvement really as it's unlikely that people send to so many addresses that this would really matter, but why not I guess.

**Comment by glensc** [comment]
it's about code style. this code will be likely source for many other projects. so it's good idea to have excellent code ;)

but what about testing, that the typo was not catched? i think the part is not tested at all.

**Comment by Seldaek** [comment]
Yeah that's well possible, we don't have tests for everything, some 
handlers are pretty hard to test and pretty low return as the code is 
simple and changes rare.

**Comment by glensc** [comment]
as i understand this can be easily tested to avoid calling native `mail()`?

i.e declare `mail()` in `Monolog\Handler` namespace, and the handler will call `\Monolog\Handler\mail()` function not `\mail()`, right?

**Comment by Seldaek** [comment]
Yup I think so as well, feel free to give it a shot if you like, the 
more tests the better I am not gonna argue with that :)

**Pull request merged**
