### PR TITLE
Discord handler

### PR DESCRIPTION
**Pull request by Crecket**
A basic discord handler using the Bot api over HTTPS which can be found here: https://discordapp.com/developers/docs/reference

A quick example:
```PHP
$discordHandler = new \Monolog\Handler\DiscordBotHandler($channel_id, $bot_token, Logger::ERROR);
$discordHandler->setEmoji(':warning:');
$monolog->pushHandler($discordHandler);

$monolog->error('Wew something went terribly wrong!');
```
This will output something similar to this:
56d5896d8e96e32dcd98735df826976c

### CODE REVIEW

**Comment by Crecket** [comment]
I was just wondering if this is going to be accepted or not since I haven't received any kind of feedback/response. 

I've been using it in production on a high-traffic website since I created the pull request to log all 5xx errors and I've noticed 0 problems.

**Comment by Seldaek** [comment]
Sorry for the delay, but I'd rather not add new handlers to the 1.x release at this point, and I need to wrap up some stuff for the 2.0 before it's final.. So it might be a bit longer still.

**Comment by Crecket** [comment]
For my personal use-case I need to use a bot. Perhaps we should allow both of them by using 2 different handlers similarly to how it is done for Slack. @galli-leo

**Comment by galli-leo** [comment]
@Crecket That might also be an option

**Comment by Seldaek** [comment]
Closing as a handler is available at https://github.com/lefuturiste/monolog-discord-handler and I rather not add more of such handlers to core monolog anyway.

**Comment by lefuturiste** [comment]
I might add later a way to send messages using a discord bot in my library.

**Pull request closed without merging**
