### PR TITLE
Add possibility to use RFC3164 for udp syslog

### PR DESCRIPTION
**Pull request by dominikkukacka**

### CODE REVIEW

**Comment by Seldaek** [comment]
Sorry but as I am not familiar with RFC3164 can you explain what the upside is of using this obsolete RFC vs RFC5424 (which is 10 years old and not exactly bleeding edge)?

**Comment by dominikkukacka** [comment]
No immediate upsides. 
But there are certain tools which only support RFC3164, e.g. the syslog plugin of logstash (https://www.elastic.co/guide/en/logstash/current/plugins-inputs-syslog.html)

**Comment by Seldaek** [comment]
Ok, well I guess it doesn't hurt to have this so will merge, thanks!

**Comment by dominikkukacka** [comment]
@Seldaek should I implement it on master as well?

**Comment by Seldaek** [comment]
No no it's been merged already

**Pull request merged**
