### PR TITLE
Adding Loki Handler

### PR DESCRIPTION
**Pull request by rrajkomar**

### CODE REVIEW

**Comment by rrajkomar** [comment]
@Seldaek Could you take a look at this PR please. It is needed to do the next part:  integrate it into the monolog Symfony bundle.
Thanks.

**Comment by Seldaek** [comment]
Please rather publish this as a standalone package and add it to https://github.com/Seldaek/monolog/wiki/Third-Party-Packages#handlers - it makes more sense than baking support for everything into monolog, we already have too many handlers.

**Comment by rrajkomar** [comment]
Ok no worries, will do this asap.
Thanks.

**Comment by Jacq** [comment]
I was just looking also for this and a quick global search only showed this: https://github.com/vyuldashev/monolog-loki
I am looking forward that standalone package @rrajkomar,  thanks!
It seems ongoing grafanacon is bringing more attention to Loki for logs :)
Jacq

**Comment by Jacq** [comment]
Any news about this?, do you need support?

**Comment by gmponos** [comment]
Hi @Jacq I am building a package https://github.com/monolog-http/monolog-http that will host http handlers over PSR18 client.. I would be happy to accept a PR about a Loki Handler... most probably you can see that the package does not contain much there.. but I will push more work over the weekend and I am hoping to have something tag soon.. but let's continue the discussion there if you wish... :)

**Comment by rrajkomar** [comment]
Working on it, 
code is almost ready, 
just need to test it in a symfony bundle as it is my primary use and write a bit of documentation

**Comment by rrajkomar** [comment]
@Jacq
Here you go.
Sorry for the delay, I've been busy lately. 
https://packagist.org/packages/itspire/monolog-loki

**Comment by gmponos** [comment]
btw I am building a tool that will be a collection of handlers using PSR18 https://github.com/monolog-http/monolog-http

If you'd like I would be happy to accept a PR there :)

**Comment by rrajkomar** [comment]
@gmponos That seems like a nice idea.  
However I don't think duplicating working maintained code at multiple locations would be a great idea.  
Although I'm not really a big fan of huge packages provide all sorts of implementation, I can however provide a PR that will reuse my own package by providing a bridge of sort if you wish.

**Comment by rrajkomar** [comment]
@gmponos I've taken a closer look at the PSR-18 and how I could use it within my package and where I use it. 
I believe I'll be able to provide a 2.0 version with PSR-18 support soon, then I'll integrate it with your package with a PR. 
Sounds good to you ?

**Comment by gmponos** [comment]
Great...

**Pull request closed without merging**
