### PR TITLE
move from abandoned package to maintained package

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by stloyd** [comment]
:+1:

**Comment by greg0ire** [comment]
Wow that was quick

**Comment by Seldaek** [comment]
No brainer so no problem to review ;)

**Comment by ismailbaskin** [comment]
@Seldaek could you tag this commit?

**Comment by stof** [comment]
@ismailbaskin this is only a dev requirement, so it does not affect any project using Monolog. This does not justify a tag by itself

**Comment by stof** [comment]
@greg0ire you forgot to update the ``suggest`` section, which is also referencing this package

**Comment by greg0ire** [comment]
Good catch @stof ! See #750

**Comment by gries** [comment]
Hi,
Could you merge it into the 1.x branch too? Also why not use the current 2.6.x Version instead of 2.4.x?

**Comment by greg0ire** [comment]
@gries `~` means the last number can change. So `~2.4` actually means `2.x`, with `4 <= x`

**Comment by gries** [comment]
thx for clearing that up, any chance of merging it in the 1.x branch anyway? I'm currently getting problems because we use the "php-amqplib/php-amqplib" version in our projects but monolog still requires the videlalvaro version.

**Comment by stof** [comment]
@gries monolog only has a dev requirements and a suggestion, so this does not impact the projects using monolog

**Comment by gries** [comment]
In this case it affects the projects if I install it with the --dev switch.
"php-amqplib/php-amqplib" and "videlalvaro/php-amqplib" use the same Namespace **PhpAmqpLib\**
So right now using monolog and php-amqplib/php-amqplib when installing --dev dependencies installs two different Versions of the class: **PhpAmqpLib\Message\AMQPMessage** for example.

**Comment by greg0ire** [comment]
Do you really think `--dev` implies installing the dev dependencies of all your dependencies?

**Comment by gries** [comment]
hmm good point my bad, maybe I should have more coffee before diving into dependency hell bugs :S

**Comment by greg0ire** [comment]
You can use `composer depends videlalvaro/php-amqplib` to see what exactly requires the legacy lib.

**Pull request merged**
