### PR TITLE
Added a test logger

### PR DESCRIPTION
**Pull request by gmponos**
Hello,

I have created a TestLogger. I hope that you feel that this fits inside your package. I know that Monolog has a `TestHandler` but I believe this is better for the following reasons:

- Simpler initialization of Logger inside tests. At the moment in order to perform my tests I need to initialize a `Logger` and then a `TestHandler`.. More properties that I have to maintain inside my code... etc etc.
- Faster tests since it does minimal work. It skips all the extra work that it is made by `Logger` class.
- Inside the TestHandler you have the `getRecords` function. Even if I retrieve all the records when I need to do simple asserts I can not.. Check this:

```
$this->assertSame(['level' => 'warning', 'message' => 'that', ['context' => []], $records[0]];
```

The record contains a lot of extra information that in my case they are not needed.

Even in your tests you had to [do unset](https://github.com/Seldaek/monolog/blob/master/tests/Monolog/Handler/TestHandlerTest.php#L53). So I don't need to have all these information like `formatted` etc etc.

All I need to test is that the API of the `LoggerInterface` class is called correctly.

### CODE REVIEW

**Comment by Seldaek** [comment]
Could you move this inside a Monolog\Test\ namespace (but still in src/)? If you also wanna help out by taking care of https://github.com/Seldaek/monolog/issues/1197 at the same time that'd be even better :)

**Comment by Seldaek** [comment]
On the other hand, I kinda wonder if this doesn't belong more in the psr/log package as it doesn't have anything monolog specific really

**Comment by gmponos** [comment]
O had the same dilemma also if I should commit it here or on the PSR. Checking PSR now again I just saw this namespace `Psr\Log\Test` so yes I believe it could fit in there. check the PR https://github.com/php-fig/log/pull/57

Thank you.

**Comment by Seldaek** [comment]
Ok gonna close this here then.

**Comment by gmponos** [comment]
Hi @Seldaek do you think that this could be added in here now that the TestLogger is removed from `psr/log` ?

**Comment by stof** [comment]
@gmponos as there is still nothing specific to Monolog in that TestLogger (the monolog-specific way is to use the TestHandler of Monolog), you can maintain that in its own package.

**Pull request closed without merging**
