### PR TITLE
Make PHP7 and HHVM builds optional

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
They failed in the last bunch of TravisCI builds

### CODE REVIEW

**Comment by stof** [comment]
The HHVM failure seems a big in PHPUnit_Mock_Object. It should be reported to PHPUnit.

For PHP 7, there is 2 things to change:

- we should not try to enable the AMQP and Mongo extensions, as done for HHVM, given they are not yet compatible with PHP 7
- we should report an issue to Elastica about the PHP 7 compatibility

**Comment by stof** [comment]
For Elastica, I reported it at https://github.com/ruflin/Elastica/issues/825

**Comment by JeroenDeDauw** [comment]
By no means am I suggesting that these issues should not be fixed. However, since doing so takes time, it does seem good to mark these builds as optional until they can be made required again.

**Comment by stof** [comment]
@JeroenDeDauw I totally agree about making these optional. However, if issues are not reported upstream, they might never get fixed.

**Comment by bd808** [comment]
@stof The HHVM failure is a known issue for both [PHPUnit](https://github.com/sebastianbergmann/phpunit-mock-objects/issues/223) and [HHVM](https://github.com/facebook/hhvm/issues/5170). The underlying HHVM bug has been marked as fixed but apparently isn't in the builds used by Travis yet.

**Comment by stof** [comment]
@bd808 this is because the fix in HHVM is not yet released

**Comment by Seldaek** [comment]
Build is now fixed

**Pull request closed without merging**
