### PR TITLE
Catch Throwable

### PR DESCRIPTION
**Pull request by fprochazka**
I'm not 100% sure about adding the catch everywhere, but here it is, let's have a discussion about it.

Related #790

### CODE REVIEW

**Comment by stof** [comment]
makes sense to me

**Comment by moderndeveloperllc** [comment]
With `master` being PHP 7 only (check `composer.json`), you can take out the `\Exception` call and only call `\Throwable`. I don't thing @Seldaek, or anyone else, has gone through the codebase yet to change all these over. I have #785 that does it in another file.

**Comment by xabbuh** [comment]
Though the change as it is right now could make sense in 1.x too.

**Comment by fprochazka** [comment]
@moderndeveloperllc cool, I didn't notice that :+1:

**Comment by fprochazka** [comment]
So, should I also open a PR against `1.x` ?

**Comment by moderndeveloperllc** [comment]
@xabbuh Putting PHP 7 code into 1.x doesn't make much sense as the main reason (I believe) for going to a 2.x release is PHP 7. I'm not even sure the 1.x library works in 7. By bifurcating the code, it eliminates the need to have this kind of duplication or version checking.

@Seldaek, can we get a definitive ruling on putting PHP 7 code in the 1.x branch?

**Comment by stof** [comment]
@moderndeveloperllc the 1.x branch is compatible with PHP 7 yes (it cannot depend on new features added in PHP 7).
Making this handler aimed at hiding errors hide all of them looks sensible to me.

**Comment by stof** [comment]
We would have to catch both Exception and Throwable in 1.x though (which was done in this PR initially)

**Pull request merged**
