### PR TITLE
Update NormalizerFormatter.php

### PR DESCRIPTION
**Pull request by draev**
Some objects implement magic __toString method
Allow to print this kind of objects in the logger

### CODE REVIEW

**Comment by draev** [comment]
@draev is fixing tests..

**Comment by Seldaek** [comment]
Looks good but yes fixing tests would be nice

**Comment by Seldaek** [comment]
Well actually no it's not good, it should check if the object does not implement [JsonSerializable](http://php.net/manual/en/class.jsonserializable.php) before and if it does skip the __toString check because json_encode will do the right thing.

**Comment by draev** [comment]
yep, good observation ;)

**Comment by Seldaek** [comment]
Thanks!

**Pull request merged**
