### PR TITLE
Allow GroupHandler to set a formatter to all nested handlers

### PR DESCRIPTION
**Pull request by eexit**
Hello,

I would like to know if it's possible to add such shortcut for the `GroupHandler`?

Thanks,

### CODE REVIEW

**Comment by Seldaek** [comment]
Why not I guess..

**Comment by eexit** [comment]
Thanks @Seldaek!

**Comment by eexit** [comment]
Should I port the change to the master branch?

**Comment by Seldaek** [comment]
No I'll merge 1.x into master myself it's easier to keep the branches consistent that way I think but thanks :)

**Pull request merged**
