### PR TITLE
Normalization of arrays containing self references

### PR DESCRIPTION
**Pull request by deviantintegral**
Backport of #808 for issue #924 .

`Monolog\Handler\StreamHandlerTest::testWriteNonExistingResource` is hanging on my machine on 1.x, so we'll see what happens in Travis.

### CODE REVIEW

**Comment by juampynr** [comment]
Tested it. Works fine.

**Comment by Seldaek** [comment]
Thanks but due to conflicts I'd rather not backport this. I'm trying to get 2.0 released soon though.

**Comment by deviantintegral** [comment]
Are you open to merging this if I backport it? Or are you not planning on doing any more releases on 1.x? We've seen this come up with Drupal sites quite a bit, as logs often include a backtrace as a context variable.

**Comment by Seldaek** [comment]
Hm well I guess maybe it can be backported without too much problems, I'll give it a shot.

**Comment by deviantintegral** [comment]
Conflicts resolved and tests pass.

**Comment by Seldaek** [comment]
Thanks

**Pull request merged**
