### PR TITLE
timestamped index in elastica and elasticseach formatter

### PR DESCRIPTION
**Pull request by hervelaunay**
copy of https://github.com/Seldaek/monolog/pull/1338 for the new monolg release

### CODE REVIEW

**Comment by Seldaek** [comment]
Closing as we need to figure out if/where to merge this first in the other PR, if it gets merged in 1.x it will be then merged in master automatically.

**Comment by hervelaunay** [comment]
This not realy the same pull request because in the new version there is a new elasticsearch handler replacing the elastica one.

**Comment by Seldaek** [comment]
Sorry missed that, reopening.

**Comment by alexandrmazur96** [comment]
@hervelaunay this PR fail 2 tests, can you fix it?

**Pull request closed without merging**
