### PR TITLE
Add missed return phpdoc tag.

### PR DESCRIPTION
**Pull request by Aliance**

### CODE REVIEW

**Comment by Seldaek** [comment]
Please use `@return self` if anything, and send the pull request against the 1.x branch, because in master branch it targets php7 and should just be `function setRelease($release): self`.

**Comment by Aliance** [comment]
May I edit this pr (branch can be edited, you need just to reopen it) & make another for php7 branch?

**Comment by Seldaek** [comment]
You can open a new PR from a new branch or the same branch.. up to you as long as it goes to the right branch here :) I can reopen if you like but it doesn't matter much.

**Comment by Aliance** [comment]
Do not like reopening because of 'broken' pr ID :rofl: Nevermind, do I make the right changes?

**Comment by Aliance** [comment]
What about adding `.idea` directory to the git ignore?

**Comment by Aliance** [comment]
@Seldaek any response?

**Comment by staabm** [comment]
> What about adding .idea directory to the git ignore?

usually you should have that in your global gitconfig instead of each project

**Pull request merged**
