### PR TITLE
Reset test handler

### PR DESCRIPTION
**Pull request by gmponos**
Shouldn't the test handler be reset as well?

### CODE REVIEW

**Comment by Seldaek** [comment]
Seems reasonable yes :) Thanks

**Comment by Seldaek** [comment]
Seems to break tests though..

**Comment by gmponos** [comment]
I can't seem to be able to fix the tests though.. I would like some help here.. if the test that fails make sense to you in the way it is write now..

**Comment by Seldaek** [comment]
Fixed in https://github.com/Seldaek/monolog/commit/a335f6f1a564f43d2c63f2eeeca381e6c78f9006 - those tests rely on reset happening at the buffer/fingerscrossed handler but at that point they flush their buffer to their inner test handler so if that one gets reset then it just doesn't work.

**Pull request merged**
