### PR TITLE
Catch Throwable

### PR DESCRIPTION
**Pull request by fprochazka**
Related #788

### CODE REVIEW

**Comment by fprochazka** [comment]
@Seldaek this shouldn't have been merged into master https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/WhatFailureGroupHandler.php

**Comment by Seldaek** [comment]
Well it had to but now it needs to be cleaned up yeah :)

**Comment by Seldaek** [comment]
I'll do it BTW :)

**Comment by fprochazka** [comment]
@Seldaek Ok, thanks :)

**Pull request merged**
