### PR TITLE
Custom exception handler (#500)

### PR DESCRIPTION
**Pull request by vincepare**
Handlers, processors and formatters may rise exceptions while logging a record, and if the user does not wrap each Monolog calls with a try/catch, this will crash the entire app (#500). Using a WhatFailureGroupHandler seems to have [some downsides](https://github.com/Seldaek/monolog/issues/946).

So this pull request aims to keep Monolog's default behavior unchanged while allowing users to define their own default behavior through a callback, and for example turn Monolog exceptions to PHP Warnings, or change the HTTP response code.

### CODE REVIEW

**Comment by adjenks** [comment]
I did this on our site:


```
use Monolog\Handler\StreamHandler;

/**
 * Handles logging with grace. (Proceeds to next handler on Exceptions)
 *
 * Was created because the standard logger does not have the ability to fall 
 * back to another handler when one dies.
 */
class GracefulLogger extends \Monolog\Logger
{

	/**
     * Handler for throwables thrown by handlers
     *
     * To handle errors thrown by handlers, letting the next handler continue if one fails.
	 * Set to call error_log by default so you can debug any log handlers that fail
     *
     * @var callable
     */
	protected $handlerExceptionHandler;

    /**
     * @param string             $name       The logging channel
     * @param HandlerInterface[] $handlers   Optional stack of handlers, the first one in the array is called first, etc.
     * @param callable[]         $processors Optional array of processors
	 * @param \Closure           $handlerExceptionHandler The function to pass exceptions to when a handler fails. Defaults to error_log();
     */
    public function __construct($name, array $handlers = array(), array $processors = array(), \Closure $handlerExceptionHandler = null)
    {
        parent::__construct($name, $handlers, $processors);
		$this->handlerExceptionHandler = is_callable($handlerExceptionHandler) ? $handlerExceptionHandler : function($e){error_log($e);};
    }


    /**
     * Adds a log record.
     *
     * @param  int     $level   The logging level
     * @param  string  $message The log message
     * @param  array   $context The log context
     * @return Boolean Whether the record has been processed
     */
    public function addRecord($level, $message, array $context = array())
    {
        if (!$this->handlers) {
            $this->pushHandler(new StreamHandler('php://stderr', static::DEBUG));
        }

        $levelName = static::getLevelName($level);

        // check if any handler will handle this message so we can return early and save cycles
        $handlerKey = null;
        reset($this->handlers);
        while ($handler = current($this->handlers)) {
            if ($handler->isHandling(array('level' => $level))) {
                $handlerKey = key($this->handlers);
                break;
            }

            next($this->handlers);
        }

        if (null === $handlerKey) {
            return false;
        }

        if (!static::$timezone) {
            static::$timezone = new \DateTimeZone(date_default_timezone_get() ?: 'UTC');
        }

        // php7.1+ always has microseconds enabled, so we do not need this hack
        if ($this->microsecondTimestamps && PHP_VERSION_ID < 70100) {
            $ts = \DateTime::createFromFormat('U.u', sprintf('%.6F', microtime(true)), static::$timezone);
        } else {
            $ts = new \DateTime(null, static::$timezone);
        }
        $ts->setTimezone(static::$timezone);

        $record = array(
            'message' => (string) $message,
            'context' => $context,
            'level' => $level,
            'level_name' => $levelName,
            'channel' => $this->name,
            'datetime' => $ts,
            'extra' => array(),
        );

        foreach ($this->processors as $processor) {
            $record = call_user_func($processor, $record);
        }

		$stopBubble = false;
		
        while ($handler = current($this->handlers)) {
			try{
				$stopBubble = $handler->handle($record);
			}catch(\Throwable $e){ //php7
				($this->handlerExceptionHandler)($e); //brackets to explicitly indicate it is a function
			}catch(\Exception $e){ //php<7
				($this->handlerExceptionHandler)($e);
			}
			
            if ($stopBubble) {
                break;
            }

            next($this->handlers);
        }

        return true;
    }

}

```

**Comment by adjenks** [comment]
Oh, my mistake, I didn't look at the code until now. Looks good, kinda like what I did except it looks more thorough.

**Comment by adjenks** [comment]
I like that you made a setExceptionHandler() function instead of making the constructor take even more arguments like I did. You didn't want to call it setHandlerExceptionHandler()? Haha. Since it handles the exceptions of the handlers.

**Comment by Seldaek** [comment]
Thanks, this is a good compromise I guess to allow people to handle errors in their own way.

**Pull request merged**
