### PR TITLE
Delete SlackbotHandler

### PR DESCRIPTION
**Pull request by gmponos**
After contacting slack I have confirmed that this is a deprecated API.

So we can get rid of this handler and have less maintenance cost now on v2 of monolog.

### CODE REVIEW

**Comment by stof** [comment]
should also be marked as deprecated in 1.x

**Comment by gmponos** [comment]
@stof you are correct.. done here https://github.com/Seldaek/monolog/pull/1257.. have a look if you wish :)

**Comment by gmponos** [comment]
Marking this as WIP because the deprecation must be merged first and then we must merge this to avoid any conflicts.

**Comment by Seldaek** [comment]
Let me merge 1.x into master and then you can rebase this cleanly.. Patience ;)

**Comment by Seldaek** [comment]
Ok merge done

**Comment by gmponos** [comment]
> Let me merge 1.x into master and then you can rebase this cleanly.. Patience ;)

Sorry for that :) 👍

**Comment by Seldaek** [comment]
Thanks

**Pull request merged**
