### PR TITLE
make methods protected access level so developer can override

### PR DESCRIPTION
**Pull request by milos-silni**

### CODE REVIEW

**Comment by stof** [comment]
This makes the maintenance a lot harder. Allowing protected access to properties means it is almost impossible to refactor the class without it being a BC break.

Please describe the use case you have that would justify that cost.

**Comment by milos-silni** [comment]
> This makes the maintenance a lot harder. Allowing protected access to properties means it is almost impossible to refactor the class without it being a BC break.
> 
> Please describe the use case you have that would justify that cost.

I wanted to override writingIsTimedOut method and add option to use ms instead of seconds

**Comment by milos-silni** [comment]
in that case i will create a new pull request with changes from comment above

**Comment by Seldaek** [comment]
Closing as #1517 is indeed a much better approach than overriding code :)

**Pull request closed without merging**
