### PR TITLE
Created Pusher.com Handler

### PR DESCRIPTION
**Pull request by rosscdh**
Please review

### CODE REVIEW

**Comment by jrobeson** [comment]
@rosscdh : are you gonna work on this in the future?

**Comment by Seldaek** [comment]
@jrobeson this seems kinda dead so if you want to use it feel free to grab it and run with it, I'd release it as a third party handler package so it can require the pusher package.

**Comment by rosscdh** [comment]
@jrobeson sorry guys, I dont work much with PHP anymore. But feel free to use the code in any way you like.

**Comment by Seldaek** [comment]
Closing as it's very old, it can always be done as an third party handler package if anyone really wants.

**Pull request closed without merging**
