### PR TITLE
FingersCrossedHandler fix passthruLevel checking (Fixes #1800)

### LINKED ISSUE #1800: FingersCrossedHandler Does not check passthruLevel properly
Monolog version 3.2.1

FingersCrossedHandler have an option to passthrough log line above certain level without writing out every other lines in the request.
The filtering logic check each buffered log line if it is above or equals to the passthrough level threshold.

The level has been changed to enum, which means a simple more-than comparison will no longer work.
https://github.com/Seldaek/monolog/blob/b05bf55097060ec20f49ccec0cf2f8e5aaa468b3/src/Monolog/Handler/FingersCrossedHandler.php#L185-L187
Should be
```php
return $record->level->value >= $level->value;
```
or better
```php
return $level->includes($record->level);
```

We should also update test to cover this case.
https://github.com/Seldaek/monolog/blob/b05bf55097060ec20f49ccec0cf2f8e5aaa468b3/tests/Monolog/Handler/FingersCrossedHandlerTest.php#L253-L265

### PR DESCRIPTION
**Pull request by BrianMwit**
Fixes https://github.com/Seldaek/monolog/issues/1800

### CODE REVIEW

**Review by kkreft — APPROVED** [review]

**Review by kubawerlos — APPROVED** [review]

**Review by wopoczynski — APPROVED** [review]

**Comment by kkreft** [comment]
@stof Do we need anything else to merge it and release the fix? I'm kinda interested in that particular change and happy to help 😄 

BTW thx for maintaining this ❤️

**Comment by kkreft** [comment]
@Seldaek Hi, same question as above - what can I do to help make this change merged? 😄

**Review by ciesliklukasz — APPROVED** [review]

**Comment by stof** [comment]
@kkreft we need to wait for @Seldaek to see this PR.
I'm helping reviewing PRs on that repository but I don't have any collaborator access on it, so I cannot merge anything myself.

**Review by JohJohan — APPROVED** [review]

**Comment by Seldaek** [comment]
Sorry for the delay everyone, it's been busy times here :) Thanks for the fix tho, I'll try and get a release out soon.

**Pull request merged**
