### PR TITLE
include $context in error_handler

### PR DESCRIPTION
**Pull request by s4msung**
Very usefull to have the context included for error_handler

### CODE REVIEW

**Comment by ovr** [comment]
ping @Seldaek

**Comment by Seldaek** [comment]
Merged in 1.x, thanks

**Comment by nickel715** [comment]
context might be helpful indeed, but if you have a large amount of logs or a large amount of local vars the size of the logs explodes...

Another problem: if you use elasticsearch for logging, you run into issues if the var with the same name is in one log a string and in another log an array. Good explanation can be found [here](http://blog.endpoint.com/2013/04/elasticsearch-object-mapping-eof-400.html)

Maybe it would be better to make the context logging optional? So you have to enable it explicit

**Comment by Seldaek** [comment]
Oh I see.. I didn't realize the context was *everything defined in the current scope*. That can get quite large indeed. I am not sure how to best handle this though. An option surely is possible, but I wonder in which cases it really makes sense to have this on. Can we get more info from @s4msung  and $ovr?

**Comment by s4msung** [comment]
+1 for reverting this PR

Reason: http://php.net/manual/en/function.set-error-handler.php
errcontext is a reference to existing variables (local and superglobal scope afaik) and should not be modified. If you modify $errcontext, you will be modifying those existing variables (e.g. Formatters)

**Comment by eclipxe13** [comment]
+1 on revert this, or at least make it optional.

When using on a legacy project that uses trigger_error it enter to infinite loops and never register the warning

```
Fatal error: Maximum function nesting level of '256' reached, aborting! in /home/eclipxe/websites/daymx/includes/monolog/monolog/src/Monolog/ErrorHandler.php on line 165

Call Stack:
    0.0002     353768   1. {main}() /project/application/www/errors.php:0
    0.0292    1580664   2. trigger_error() /project/application/www/errors.php:12
    0.0292    1583392   3. Monolog\ErrorHandler->handleError() /project/application/www/errors.php:12
    0.0292    1583816   4. Monolog\Logger->log() /project/includes/monolog/monolog/src/Monolog/ErrorHandler.php:152
    0.0293    1583816   5. Monolog\Logger->addRecord() /project/includes/monolog/monolog/src/Monolog/Logger.php:517
    0.0310    1637304   6. Monolog\Handler\AbstractProcessingHandler->handle() /project/includes/monolog/monolog/src/Monolog/Logger.php:336
    0.0328    1709456   7. Monolog\Formatter\LineFormatter->format() /project/includes/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php:35
    0.0328    1709456   8. Monolog\Formatter\NormalizerFormatter->format() /project/includes/monolog/monolog/src/Monolog/Formatter/LineFormatter.php:68
    0.0328    1709456   9. Monolog\Formatter\NormalizerFormatter->normalize() /project/includes/monolog/monolog/src/Monolog/Formatter/NormalizerFormatter.php:43
    0.0328    1709832  10. Monolog\Formatter\NormalizerFormatter->normalize() /project/includes/monolog/monolog/src/Monolog/Formatter/NormalizerFormatter.php:82
...
    0.1414    2856584 256. Monolog\Formatter\NormalizerFormatter->normalize() /project/includes/monolog/monolog/src/Monolog/Formatter/NormalizerFormatter.php:82
```

This is the basic php script:
```php
<?php
// composer, its not installed on vendor
require __DIR__ . '/../../includes/autoload.php';

error_reporting(-1);
ini_set("display_errors", "1");
ini_set("log_errors", "0");

$logger = new Monolog\Logger('test');
Monolog\ErrorHandler::register($logger);

trigger_error('test', E_USER_WARNING);
```

After removing the `$context` from `src/Monolog/ErrorHandler.php:152` everything works as usual.
```
[2016-07-17 21:58:48] test.WARNING: E_USER_WARNING: test {"code":512,"message":"test","file":"/project/application/www/errors.php","line":12} []

Warning: test in /project/application/www/errors.php on line 12

Call Stack:
    0.0002     353768   1. {main}() /project/application/www/errors.php:0
    0.0294    1580664   2. trigger_error() /project/application/www/errors.php:12
```

**Comment by nickel715** [comment]
@Seldaek What's the current state? 
Meanwhile I also ran into the error described by @eclipxe13. 
When can we expect the release of the revert?

**Comment by Seldaek** [comment]
I reverted this entirely because I don't see it feasible. Sorry @s4msung but if you really need the context info in your project I suggest you register your own error handler, it's really not that much code anyway.

**Comment by eclipxe13** [comment]
Great! I can confirm that everything back to normal with version 1.21.0. Thanks!

**Pull request closed without merging**
