### PR TITLE
#508 add hasLogger method to Monolog\Registry

### PR DESCRIPTION
**Pull request by theravel**

### CODE REVIEW

**Comment by rantonmattei** [comment]
@Seldaek can we get this PR merged?

**Comment by Seldaek** [comment]
Yup sorry I missed this new PR, thanks!

**Comment by rantonmattei** [comment]
For reference purposes.
This is a patch for issue https://github.com/Seldaek/monolog/issues/508

**Comment by rantonmattei** [comment]
hi @Seldaek , when can we expect this to be released? When are you planning to cut a new tag?

**Comment by Seldaek** [comment]
I'll need some more time to review other open PRs before tagging, hopefully around this weekend?

**Comment by rantonmattei** [comment]
Ok, sounds good I was wondering what your process was and wanted to make sure it did not fall through the cracks :grin: 
Thanks for you quick answer!

**Comment by Seldaek** [comment]
1.13 is out!

**Pull request merged**
