### PR TITLE
Ignore "call_user_func" from debug backtrace

### PR DESCRIPTION
**Pull request by xploSEoF**
Helps make this compliant where there is no class defined

### CODE REVIEW

**Comment by staabm** [comment]
what about `call_user_func_array`?

**Comment by stof** [comment]
and please don't break the formatting of the code. This library follows PSR-2, which implies indenting with spaces. Your modified code seems to use tabs, messing the formatting (see the diff)

**Comment by xploSEoF** [comment]
Feel free to change it - space indented stuff seems to mess up on me, and I'm not waiting on these PRs

**Comment by stof** [comment]
well, I'm not maintainer on this repo. I just looked at the PR before the maintainer.

**Comment by Seldaek** [comment]
thanks

**Pull request merged**
