### PR TITLE
Change out Exception to Throwable

### PR DESCRIPTION
**Pull request by moderndeveloperllc**
Looks like these were TODOs for 2.0, so might as well get these out of the way.

### CODE REVIEW

**Comment by staabm** [comment]
After this change you need to uplift php version constraint to >=7.0

**Comment by moderndeveloperllc** [comment]
@staabm The `master` branch is already at that.
```
"require": {
    "php": "^7.0",
    "psr/log": "^1.0"
},
```

**Comment by staabm** [comment]
Then its fine :)

**Comment by Seldaek** [comment]
Thanks

**Pull request merged**
