### PR TITLE
Fix: Wrong raven/raven version

### PR DESCRIPTION
**Pull request by mabrahamde**
RavenHandler uses Raven_Client::user_context(). This method is available since 0.8.0.

see https://github.com/getsentry/raven-php/commit/7dd1fb3a353eb2b456336a996e5265fc5756a085

### CODE REVIEW

**Comment by mabrahamde** [comment]
Anything wrong with this one? It just fixes a small bug inside dependency management. Build status is same as mainline.

**Comment by smazurov** [comment]
`~0.5` translates to `>=0.5.0 < 1.0.0` in composer. [See this](https://getcomposer.org/doc/01-basic-usage.md#package-versions)

**Comment by Seldaek** [comment]
Indeed it seems just fine as it is.

**Comment by mabrahamde** [comment]
I does not make sense to require raven/raven versions < 0.8.0. Monolog is using functionality which is missing there. 

If there is a raven/raven 0.5.x package installed already...and you installing monolog via composer afterwards

- the unsupported 0.5.x version of raven/raven will not get updated
- no warning/conflict will be displayed during installation
- logging to sentry will fail.

Monolog requires raven/raven version >= 0.8.0 < 1.0.0 which translates to ~0.8.

**Comment by Seldaek** [comment]
Right sorry for the misunderstanding, I checked and indeed it segfaults with 0.5 - 0.7 versions.

**Comment by mabrahamde** [comment]
:+1:

**Pull request merged**
